<a href="https://colab.research.google.com/github/JonathanIS10/prueba2/blob/main/NumPy_Exercises_for_Data_Analysis_JonathanIntriago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np. __version__


'1.22.4'

In [3]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[1 2 3 4 5 6 7 8 9]


In [4]:
array = np.ones((3, 3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

[ True  True  True  True  True  True  True  True  True]


In [6]:
array[array % 2 != 0] = -1
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
matriz1d= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matriz2d = matriz1d.reshape(2, -1)
print(matriz2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.vstack((A, B))
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.hstack((A, B))
print(stacked)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a = np.arange(15)
print(a[5:11])

[ 5  6  7  8  9 10]


In [11]:
def suma_escalar(matriz, escalar):
    resultado = np.add(matriz, escalar)
    return resultado
    a = np.array([5, 7, 9, 8, 6, 4, 5])
    b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = suma_escalar(a, b)
print(resultado)

NameError: ignored

In [12]:
matriz = np.array([[4, 5, 1], [2, 3, 7], [6, 8, 9]])
matriz[:, [1, 2]] = matriz[:, [2, 1]]
print(matriz)

[[4 1 5]
 [2 7 3]
 [6 9 8]]


In [13]:
matriz = np.random.uniform(5, 10, size=(5, 3))
print(matriz)

[[6.97401028 5.36137642 5.85159202]
 [8.16830426 9.36064787 6.71035541]
 [6.43370491 9.51425253 6.45452964]
 [9.73286417 7.15354746 6.66739365]
 [7.33070604 6.46641196 5.13780455]]
